### ISSUE TITLE
Vanishing Blocks and Resurrecting After Death

### ISSUE THREAD

**Issue by ReSharplex** [ReSharplex/ReMiNET#2]
When you die, strange things can happen inside chunk, like blocks you placed disappearing and then coming back after a few deaths

**Comment by ReSharplex** [comment]
but maybe not always inside chunk

**Comment by CobwebSMP** [comment]
I didn't even know about this as I haven't tested or used anything much related survival mode.
But cause of this has been found and will be fixed.

**Comment by ReSharplex** [comment]
Thanks for fixing it. I wasn't even sure if you'd check the issues
